name: auto-ls-svm-env
channels:
 - defaults
 - conda-forge
dependencies:
 - python=3
 - pandas
 - scikit-learn
 - numpy
 - scipy
 - matplotlib
 - seaborn
 - requests
 - beautifulsoup4
 - tqdm
 - jupyter
 - pytest
 - nose
